### ISSUE TITLE
Player list ranking table not creating

### ISSUE THREAD

**Issue by adiromar** [ThemeBoy/SportsPress-for-Cricket#2]
Warning: number_format() expects parameter 2 to be integer, string given in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\class-sp-player-list.php on line 500

Warning: number_format() expects parameter 2 to be integer, string given in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\class-sp-player-list.php on line 500

Warning: number_format() expects parameter 2 to be integer, string given in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\class-sp-player-list.php on line 500

Warning: number_format() expects parameter 2 to be integer, string given in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\class-sp-player-list.php on line 500

Fatal error: Uncaught Exception: Variable replacement does not exist for 'wkt' in $wkts in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\libraries\class-eqeos.php:375 Stack trace: #0 C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\sp-core-functions.php(1250): eqEOS->solveIF('$wkts', Array) #1 C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\class-sp-player-list.php(493): sp_solve('($o*6)/$wkts', Array, '2') #2 C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\admin\post-types\meta-boxes\class-sp-meta-box-list-data.php(23): SP_Player_List->data(true) #3 C:\xampp\htdocs\website.com\wp-admin\includes\template.php(1048): SP_Meta_Box_List_Data::output(Object(WP_Post), Array) #4 C:\xampp\htdocs\website.com\wp-admin\edit-form-advanced.php(703): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post)) #5 C:\xampp\htdocs\website.com\wp-admin\post.php(173): include('C:\\xampp\\htdocs...') #6 {main} thrown in C:\xampp\htdocs\website.com\wp-content\plugins\sportspress\includes\libraries\class-eqeos.php on line 375

**Comment by adiromar** [comment]
@ThemeBoy please fix the issue..

**Comment by brianmiyaji** [comment]
@adiromar does this commit fix this issue? https://github.com/ThemeBoy/SportsPress/commit/7bc729dfd17f784ab275eeb31215f690f2f71ca0#diff-7241590d6e1ca7f1fbf75a074ee537d2

**Comment by adiromar** [comment]
@brianmiyaji how to add **highest score** and **_best bowling figures_** in Player's List..
